### ISSUE TITLE
Use hadoop-lzo 0.4.20 from Snowplow Bintray maven

### ISSUE THREAD

**Issue by benjben** [snowplow/snowplow-s3-loader#183]
Otherwise
```
[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: com.hadoop.gplcompression#hadoop-lzo;0.4.20: not found
```

**Comment by benjben** [comment]
Add `org.apache.commons.collections` dependency otherwise when bumping Scala version and all the libs it is failing with:
```
[error] Caused by: java.lang.ClassNotFoundException: org.apache.commons.collections.map.UnmodifiableMap
[error]         at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[error]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[error]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[error]         at org.apache.hadoop.conf.Configuration$DeprecationContext.<init>(Configuration.java:409)
[error]         at org.apache.hadoop.conf.Configuration.<clinit>(Configuration.java:448)
[error]         at com.snowplowanalytics.s3.loader.serializers.LzoSerializer$.<clinit>(LzoSerializer.scala:38)
[error]         at com.snowplowanalytics.s3.loader.serializers.LzoSerializerSpec.$anonfun$new$2(LzoSerializerSpec.scala:69)
```
It seems that so far we've been lucky enough that this class was in the classpath, but with the bump of all the libraries it's not any more.
