### ISSUE TITLE
sbt assembly fails on centos 7

### ISSUE THREAD

**Issue by mochini** [snowplow/snowplow-s3-loader#196]
Trying to get this up and running on aws/centos 7

This was the output from 'sbt assembly':

[info] welcome to sbt 1.4.4 (Red Hat, Inc. Java 1.8.0_275)
[info] loading settings for project snowplow-s3-loader-build from plugins.sbt ...
[info] loading project definition from /opt/snowplow-s3-loader/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] compiling 2 Scala sources to /opt/snowplow-s3-loader/project/target/scala-2.12/sbt-1.0/classes ...
[info] loading settings for project root from build.sbt ...
[info] set current project to snowplow-s3-loader (in build file:/opt/snowplow-s3-loader/)
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] compiling 23 Scala sources to /opt/snowplow-s3-loader/target/scala-2.13/classes ...
[info] compiling 4 Scala sources to /opt/snowplow-s3-loader/target/scala-2.13/test-classes ...
[info] DynamicPathSpec
[info] DynamicPathSpec should
[info]   + correctly decorate Time formats with one time pattern
[info]   + correctly decorate Time formats with multiple time patterns
[info]   + correctly decorate Time formats with extra trailing slash
[info]   + correctly decorate Time formats with invalid time format
[info]   + correctly handle no format
[info] Total for specification DynamicPathSpec
[info] Finished in 698 ms
[info] 5 examples, 0 failure, 0 error
[info] KinesisS3EmitterSpec
[info] KinesisS3Emitter should
[info]   + correctly decorate Time formats with one time pattern
[info]   + correctly decorate Time formats with multiple time patterns
[info]   + correctly decorate Time formats with extra trailing slash
[info]   + correctly decorate Time formats with invalid time format
[info]   + correctly handle no format
[info] Total for specification DynamicPathSpec
[info] Finished in 698 ms
[info] 5 examples, 0 failure, 0 error
[info] KinesisS3EmitterSpec
[info] KinesisS3Emitter should
[info]   + format file name with optional components
[info]   + format file name without optional components
[info]   + partition records correctly according to schema key
[info]   + handle empty list of records to partition
[info] Total for specification KinesisS3EmitterSpec
[info] Finished in 876 ms
[info] 4 examples, 0 failure, 0 error
[specs2-2] INFO com.hadoop.compression.lzo.GPLNativeCodeLoader - Loaded native gpl library from the embedded binaries
[specs2-2] INFO com.hadoop.compression.lzo.LzoCodec - Successfully loaded & initialized native-lzo library [hadoop-lzo rev 52decc77982b58949890770d22720a91adce0c3f]
[specs2-2] INFO org.apache.hadoop.conf.Configuration.deprecation - hadoop.native.lib is deprecated. Instead, use io.native.lib.available
[specs2-2] INFO org.apache.hadoop.io.compress.CodecPool - Got brand-new compressor [.lzo]
[info] LzoSerializerSpec
[info] The LzoSerializer should
[info]   + correctly serialize and compress a list of CollectorPayloads
[info] Total for specification LzoSerializerSpec
[info] Finished in 998 ms
[info] 1 example, 3 expectations, 0 failure, 0 error
[info] GZipSerializerSpec
[info] The GZipSerializer should
[info]   + correctly serialize and compress a list of CollectorPayloads
[info] Total for specification GZipSerializerSpec
[info] Finished in 210 ms
[info] 1 example, 3 expectations, 0 failure, 0 error
[info] Passed: Total 11, Failed 0, Errors 0, Passed 11
[error] 29 errors were encountered during merge
[error] java.lang.RuntimeException: deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/Appender.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/Appender.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/AppenderSkeleton.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/AppenderSkeleton.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/BasicConfigurator.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/BasicConfigurator.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/Category.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/Category.class

[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/ConsoleAppender.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/ConsoleAppender.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/FileAppender.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/FileAppender.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/Layout.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/Layout.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/Level.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/Level.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/LogManager.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/LogManager.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/Logger.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/Logger.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/MDC.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/MDC.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/NDC.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/NDC.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/PatternLayout.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/PatternLayout.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/Priority.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/Priority.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/PropertyConfigurator.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/PropertyConfigurator.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/RollingFileAppender.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/RollingFileAppender.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/SimpleLayout.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/SimpleLayout.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/WriterAppender.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/WriterAppender.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/helpers/LogLog.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/helpers/LogLog.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/helpers/NullEnumeration.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/helpers/NullEnumeration.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/spi/Configurator.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/spi/Configurator.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/spi/ErrorHandler.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/spi/ErrorHandler.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/spi/Filter.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/spi/Filter.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/spi/HierarchyEventListener.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/spi/HierarchyEventListener.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/spi/LoggerFactory.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/spi/LoggerFactory.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/spi/LoggerRepository.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/spi/LoggerRepository.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/spi/LoggingEvent.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/spi/LoggingEvent.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/spi/OptionHandler.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/spi/OptionHandler.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/xml/DOMConfigurator.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/xml/DOMConfigurator.class
[error]         at sbtassembly.Assembly$.applyStrategies(Assembly.scala:143)
[error]         at sbtassembly.Assembly$.x$1$lzycompute$1(Assembly.scala:25)
[error]         at sbtassembly.Assembly$.x$1$1(Assembly.scala:23)
[error]         at sbtassembly.Assembly$.stratMapping$lzycompute$1(Assembly.scala:23)
[error]         at sbtassembly.Assembly$.stratMapping$1(Assembly.scala:23)
[error]         at sbtassembly.Assembly$.inputs$lzycompute$1(Assembly.scala:68)
[error]         at sbtassembly.Assembly$.inputs$1(Assembly.scala:58)
[error]         at sbtassembly.Assembly$.apply(Assembly.scala:85)
[error]         at sbtassembly.Assembly$.$anonfun$assemblyTask$1(Assembly.scala:244)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (assembly) deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/Appender.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/Appender.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/AppenderSkeleton.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/AppenderSkeleton.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/BasicConfigurator.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/BasicConfigurator.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/Category.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/Category.class

[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/ConsoleAppender.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/ConsoleAppender.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/FileAppender.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/FileAppender.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/Layout.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/Layout.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/Level.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/Level.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/LogManager.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/LogManager.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/Logger.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/Logger.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/MDC.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/MDC.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/NDC.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/NDC.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/PatternLayout.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/PatternLayout.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/Priority.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/Priority.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/PropertyConfigurator.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/PropertyConfigurator.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/RollingFileAppender.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/RollingFileAppender.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/SimpleLayout.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/SimpleLayout.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/WriterAppender.class

[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/WriterAppender.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/helpers/LogLog.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/helpers/LogLog.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/helpers/NullEnumeration.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/helpers/NullEnumeration.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/spi/Configurator.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/spi/Configurator.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/spi/ErrorHandler.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/spi/ErrorHandler.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/spi/Filter.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/spi/Filter.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/spi/HierarchyEventListener.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/spi/HierarchyEventListener.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/spi/LoggerFactory.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/spi/LoggerFactory.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/spi/LoggerRepository.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/spi/LoggerRepository.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/spi/LoggingEvent.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/spi/LoggingEvent.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/spi/OptionHandler.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/spi/OptionHandler.class
[error] deduplicate: different file contents found in the following:
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar:org/apache/log4j/xml/DOMConfigurator.class
[error] /root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:org/apache/log4j/xml/DOMConfigurator.class
[error] Total time: 33 s, completed Jan 3, 2021 12:58:16 AM

**Comment by juanferreira** [comment]
I was able to build successfully by adding the lines below to the bottom of the build.sbt.

assemblyMergeStrategy in assembly := {
 case PathList("META-INF", xs @ _*) => MergeStrategy.discard
 case x => MergeStrategy.first
}

Afterwards, run sbt assemble and it should work.
